global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '.*duration.*|.*_total|.*_sum|.*_count|.*_bucket'
        action: keep